### ISSUE TITLE
Async plan fails on tomcat

### ISSUE THREAD

**Issue by eirikm** [unfiltered/unfiltered#269]
I'm trying to use an async plan on tomcat, but it fails with the following error:

java.lang.NullPointerException unfiltered.filter.ResponseBinding.status(bindings.scala:34) unfiltered.response.Status.respond(statuses.scala:5) unfiltered.response.Responder$class.apply(functions.scala:20) unfiltered.response.Status.apply(statuses.scala:4) unfiltered.response.ResponseFunction$$anon$1.apply(functions.scala:10) unfiltered.filter.AsyncBinding$class.respond(bindings.scala:18) unfiltered.filter.async.Plan$$anon$1.respond(plans.scala:48) no.penger.unfiltered.async.AsyncPlan$$anonfun$intent$1.applyOrElse(AsyncPlan.scala:12) no.penger.unfiltered.async.AsyncPlan$$anonfun$intent$1.applyOrElse(AsyncPlan.scala:10) scala.PartialFunction$Lifted.apply(PartialFunction.scala:218) scala.PartialFunction$Lifted.apply(PartialFunction.scala:214) unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72) unfiltered.response.Pass$PassingAttempt$class.attempt(pass.scala:65) unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67) unfiltered.response.Pass$OnPassAttempt.apply(pass.scala:88) unfiltered.filter.async.Plan$class.doFilter(plans.scala:58) no.penger.unfiltered.async.AsyncPlan.doFilter(AsyncPlan.scala:7)

Am i missing something? The exact same artifact works on jetty...

Here is a minimal project to reproduce the error:
https://github.com/eirikm/unfilteredAsyncTomcatError

I have been testing this on apache-tomcat-7.0.53.

Eirik

**Comment by elacin** [comment]
Same here, this time on jetty 9.2.10.v2015031

```
Caused by java.lang.NullPointerException - 
	at unfiltered.filter.ResponseBinding.status(bindings.scala:34)
	at unfiltered.response.Status.respond(statuses.scala:5)
	at unfiltered.response.Responder$class.apply(functions.scala:19)
	at unfiltered.response.Status.apply(statuses.scala:4)
	at unfiltered.response.ComposedResponseFunction.apply(functions.scala:36)
	at unfiltered.filter.AsyncBinding$class.respond(bindings.scala:18)
	at unfiltered.filter.async.Plan$$anon$1.respond(plans.scala:48)
    at ...
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
	at unfiltered.response.Pass$PassingAttempt$class.attempt(pass.scala:65)
	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
	at unfiltered.response.Pass$OnPassAttempt.apply(pass.scala:88)
	at unfiltered.filter.async.Plan$class.doFilter(plans.scala:58)
    at ...
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```
