### ISSUE TITLE
ResourcesSpec & PlannedResourcesSpec tests failing on Java 9 in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [unfiltered/unfiltered#418]
(on your `0.10.x` branch)

so at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/185/consoleFull we see:

```
[unfiltered:error] Exception caught handling request:
[unfiltered:error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[unfiltered:error] 	at unfiltered.netty.Mimes$.types$lzycompute(resources.scala:28)
[unfiltered:error] 	at unfiltered.netty.Mimes$.types(resources.scala:27)
[unfiltered:error] 	at unfiltered.netty.Mimes$.apply(resources.scala:29)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:115)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:75)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt$(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
[unfiltered:error] 	at unfiltered.response.Pass$OnPassAttempt.apply(pass.scala:88)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead(plans.scala:48)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead$(plans.scala:45)
[unfiltered:error] 	at unfiltered.netty.Resources.channelRead(resources.scala:55)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[unfiltered:error] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
[unfiltered:error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[unfiltered:error] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
[unfiltered:error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[unfiltered:error] Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
[unfiltered:error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
[unfiltered:error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
[unfiltered:error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[unfiltered:error] 	... 47 more
[unfiltered] [info] PlannedResourcesSpec
[unfiltered] [info] A server with resources and plans should
[unfiltered] [error]   ! respond to a resources path
[unfiltered] [error]    unfiltered.specs2.Hosted$StatusCode: 500 (Hosted.scala:43)
[unfiltered] [error] unfiltered.specs2.Hosted.http(Hosted.scala:43)
[unfiltered] [error] unfiltered.specs2.Hosted.http$(Hosted.scala:38)
[unfiltered] [error] unfiltered.netty.PlannedResourcesSpec$.http(PlannedResourcesSpec.scala:8)
[unfiltered] [error] unfiltered.netty.PlannedResourcesSpec$.$anonfun$new$3(PlannedResourcesSpec.scala:17)
[unfiltered] [error] unfiltered.netty.PlannedResourcesSpec$.$anonfun$new$2(PlannedResourcesSpec.scala:17)
[unfiltered] [info]   + respond to a plans path
[unfiltered] [info] Total for specification PlannedResourcesSpec
[unfiltered] [info] Finished in 501 ms
[unfiltered] [info] 2 examples, 4 expectations, 0 failure, 1 error
[unfiltered:error] Exception caught handling request:
[unfiltered:error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[unfiltered:error] 	at unfiltered.netty.Mimes$.types$lzycompute(resources.scala:28)
[unfiltered:error] 	at unfiltered.netty.Mimes$.types(resources.scala:27)
[unfiltered:error] 	at unfiltered.netty.Mimes$.apply(resources.scala:29)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:115)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:75)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt$(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
[unfiltered:error] 	at unfiltered.response.Pass$OnPassAttempt.apply(pass.scala:88)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead(plans.scala:48)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead$(plans.scala:45)
[unfiltered:error] 	at unfiltered.netty.Resources.channelRead(resources.scala:55)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[unfiltered:error] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
[unfiltered:error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[unfiltered:error] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
[unfiltered:error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[unfiltered:error] Exception caught handling request:
[unfiltered:error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[unfiltered:error] 	at unfiltered.netty.Mimes$.types$lzycompute(resources.scala:28)
[unfiltered:error] 	at unfiltered.netty.Mimes$.types(resources.scala:27)
[unfiltered:error] 	at unfiltered.netty.Mimes$.apply(resources.scala:29)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:115)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:75)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt$(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
[unfiltered:error] 	at unfiltered.response.Pass$OnPassAttempt.apply(pass.scala:88)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead(plans.scala:48)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead$(plans.scala:45)
[unfiltered:error] 	at unfiltered.netty.Resources.channelRead(resources.scala:55)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[unfiltered:error] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
[unfiltered:error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[unfiltered:error] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
[unfiltered:error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[unfiltered:error] Exception caught handling request:
[unfiltered:error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[unfiltered:error] 	at unfiltered.netty.Mimes$.types$lzycompute(resources.scala:28)
[unfiltered:error] 	at unfiltered.netty.Mimes$.types(resources.scala:27)
[unfiltered:error] 	at unfiltered.netty.Mimes$.apply(resources.scala:29)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:115)
[unfiltered:error] 	at unfiltered.netty.Resources$$anonfun$intent$1.applyOrElse(resources.scala:75)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
[unfiltered:error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attemptWithPass(pass.scala:72)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PassingAttempt.attempt$(pass.scala:65)
[unfiltered:error] 	at unfiltered.response.Pass$PartialAttempt.attempt(pass.scala:67)
[unfiltered:error] 	at unfiltered.response.Pass$OnPassAttempt.apply(pass.scala:88)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead(plans.scala:48)
[unfiltered:error] 	at unfiltered.netty.async.RequestPlan.channelRead$(plans.scala:45)
[unfiltered:error] 	at unfiltered.netty.Resources.channelRead(resources.scala:55)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[unfiltered:error] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[unfiltered:error] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[unfiltered:error] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[unfiltered:error] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
[unfiltered:error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
[unfiltered:error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[unfiltered:error] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
[unfiltered:error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[unfiltered] [info] ResourcesSpec
[unfiltered] [info] A resource server should
[unfiltered] [error]   x respond with a valid file
[unfiltered] [error]    'Internal Server Error' != '* { margin:0; }' (ResourcesSpec.scala:10)
[unfiltered] [error] Actual:   Internal Server Error
[unfiltered] [error] Expected: * { margin:0; }
[unfiltered] [error]   x respond with an expected Content-Type
[unfiltered] [error]    None != Some(text/html) (ResourcesSpec.scala:14)
[unfiltered] [error]   x respond with useful headers
[unfiltered] [error]    Map() doesn't have the key 'date' (ResourcesSpec.scala:22)
[unfiltered] [info]   + respond sith Forbidden (403) for requests with questionable paths
[unfiltered] [info]   + respond with NotFound (404) for requests for non-existant files
[unfiltered] [info]   + respond with Forbidden (403) for requests for a directory by default
[unfiltered] [info]   + respond with BadRequest (400) with a non GET request
[unfiltered] [info]   + respond with a NotModified (304) with a If-Modified-Since matches resources lastModified time
[unfiltered] [info] Total for specification ResourcesSpec
[unfiltered] [info] Finished in 313 ms
[unfiltered] [info] 8 examples, 10 expectations, 3 failures, 0 error
[unfiltered] [error] Error: Total 10, Failed 3, Errors 1, Passed 6
[unfiltered] [error] Failed tests:
[unfiltered] [error] 	unfiltered.netty.ResourcesSpec
[unfiltered] [error] Error during tests:
[unfiltered] [error] 	unfiltered.netty.PlannedResourcesSpec
[unfiltered] [error] (unfiltered-netty-server / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by xuwei-k** [comment]
https://github.com/unfiltered/unfiltered/pull/419

**Comment by SethTisue** [comment]
green now at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/194/console, thank you Yoshida-san
